config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get :search
    end
    resources :rates, only: [:new,:create, :destroy]
  end
  devise_for :users
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :rates


  scope :p_name, -> (name) { where(name: name)}

  def rate_avrate
    rates.average(:score).to_i
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def customeerrror

    render template: "errors/customeerrror"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # rescue_from StandardError, with: :customeerrror
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.p_name(params[:name]) if params[:name].present? 
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name).merge(user_id: current_user.id)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  
  def new
    @product = Product.find(params[:product_id])
  end
  def create
    @rate = Rate.new(rate_params)
    if @rate.save
      redirect_to root_path
    else

    end

  end

  def destroy
  end

  private
  def rate_params
   params.require(:rate).permit(:score, :comment).merge(user_id: current_user.id, product_id: params[:product_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateAp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/84d345e866.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>


<%= form_tag('/products', method: :get) do %>
  <%= text_field_tag :name%>
  <%= submit_tag '検索'%>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.user.email %></td>
        <% if product.rate_avrate == 0%>
         <td>レビューなし</td>
        <%elsif product.rate_avrate == 5%>
          <td>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>          
          </td>
        <%elsif product.rate_avrate == 4%>
          <td>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>          
          </td>

        <%elsif product.rate_avrate == 3%>
          <td>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>
          </td>

        <%elsif product.rate_avrate == 2%>
          <td>
            <i class="fas fa-star rate-good"></i>
            <i class="fas fa-star rate-good"></i>          
          </td>

        <%elsif product.rate_avrate == 1%>
          <td>
          <i class="fas fa-star rate-good"></i>
          </td>
        <%end%>
        <td></td>


        <td><%= link_to 'レビューを書く', new_product_rate_path(product) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user.email %>
</p>

<p>
    <% if @product.rate_avrate == 0%>
      レビューなし
    <%elsif @product.rate_avrate == 5%>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>          
    <%elsif @product.rate_avrate == 4%>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>          

    <%elsif @product.rate_avrate == 3%>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>
    <%elsif @product.rate_avrate == 2%>
      <i class="fas fa-star rate-good"></i>
      <i class="fas fa-star rate-good"></i>          
    <%elsif @product.rate_avrate == 1%>
      <i class="fas fa-star rate-good"></i>
    <%end%>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/rates/create.html.erb
<h1>Rates#create</h1>
<p>Find me in app/views/rates/create.html.erb</p>

app/views/rates/destroy.html.erb
<h1>Rates#destroy</h1>
<p>Find me in app/views/rates/destroy.html.erb</p>

app/views/rates/new.html.erb
<h3>レビューを書く</h3>

商品名<%= @product.name%>

<br>

<div id="stars">
  <i class="fas fa-star rate-good"></i>
  <i class="fas fa-star rate-good"></i>
  <i class="fas fa-star rate-good"></i>
  <i class="fas fa-star rate-good"></i>
  <i class="fas fa-star rate-good"></i>
</div>


<%= form_for([@product, Rate.new]) do |form|%>
  <%= form.hidden_field :score ,id: "target_value"%>
  <%= form.text_field :comment%>
  <%= form.submit%>
<%end%>